version: "3"

services:
  app:
    container_name: golang
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
    tty: true
    volumes:
      - ".:/go/src/github.com/jigintern/otacook_server"
    links:
      - db

  db:
    container_name: mysql_host
    image: mysql:5.7
    volumes:
      - "./docker/db/data:/var/lib/mysql/"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/db/sql:/docker-entrypoint-initdb.d/"
      - "./docker/log/mysql:/var/log/mysql"
    ports:
      - 3333:3306
    restart: always
    env_file:
      - .env
    tty: true
